# USER_JSON = {"data":{"id":"1","type":"users","attributes":{"name":"Anthony Rizzo","email":"arizzo@gmail.com","phone":"1111111111"},"relationships":{"memberships":{"data":[{"id":"1","type":"memberships"}]},"groups":{"data":[{"id":"1","type":"groups"}]},"events":{"data":[{"id":"1","type":"events"}]},"expenses":{"data":[{"id":"1","type":"expenses"},{"id":"2","type":"expenses"},{"id":"3","type":"expenses"}]},"bills":{"data":[]}}}}
#
# USERS_JSON = {"data":[{"id":"1","type":"users","attributes":{"name":"Anthony Rizzo","email":"arizzo@gmail.com","phone":"1111111111"},"relationships":{"memberships":{"data":[{"id":"1","type":"memberships"}]},"groups":{"data":[{"id":"1","type":"groups"}]},"events":{"data":[{"id":"1","type":"events"}]},"expenses":{"data":[{"id":"1","type":"expenses"},{"id":"2","type":"expenses"},{"id":"3","type":"expenses"}]},"bills":{"data":[]}}},{"id":"2","type":"users","attributes":{"name":"Kris Bryant","email":"kbryant@gmail.com","phone":"2222222222"},"relationships":{"memberships":{"data":[{"id":"2","type":"memberships"}]},"groups":{"data":[{"id":"1","type":"groups"}]},"events":{"data":[{"id":"1","type":"events"}]},"expenses":{"data":[{"id":"4","type":"expenses"},{"id":"5","type":"expenses"}]},"bills":{"data":[]}}},{"id":"3","type":"users","attributes":{"name":"Brad Lindgren","email":"bplindgren91@gmail.com","phone":"3333333333"},"relationships":{"memberships":{"data":[{"id":"3","type":"memberships"}]},"groups":{"data":[{"id":"1","type":"groups"}]},"events":{"data":[{"id":"1","type":"events"}]},"expenses":{"data":[{"id":"6","type":"expenses"}]},"bills":{"data":[]}}}]}
#
# USER_GROUPS_JSON = {"data":[{"id":"1","type":"groups","attributes":{"name":"Cubs"},"relationships":{"memberships":{"data":[{"id":"1","type":"memberships"},{"id":"2","type":"memberships"},{"id":"3","type":"memberships"}]},"members":{"data":[{"id":"1","type":"users"},{"id":"2","type":"users"},{"id":"3","type":"users"}]},"events":{"data":[{"id":"1","type":"events"}]},"expenses":{"data":[{"id":"1","type":"expenses"},{"id":"2","type":"expenses"},{"id":"3","type":"expenses"},{"id":"4","type":"expenses"},{"id":"5","type":"expenses"},{"id":"6","type":"expenses"}]}}}]}
#
# USER_EVENTS_JSON = {"data":[{"id":"1","type":"events","attributes":{"name":"Roadtrip","start-date":"2016-06-04T00:00:00.000Z","end-date":"2016-06-06T00:00:00.000Z","settled?":false,"group-id":1,"total":255.49},"relationships":{"group":{"data":{"id":"1","type":"groups"}},"memberships":{"data":[{"id":"1","type":"memberships"},{"id":"2","type":"memberships"},{"id":"3","type":"memberships"}]},"members":{"data":[{"id":"1","type":"users"},{"id":"2","type":"users"},{"id":"3","type":"users"}]},"expenses":{"data":[{"id":"1","type":"expenses"},{"id":"2","type":"expenses"},{"id":"3","type":"expenses"},{"id":"4","type":"expenses"},{"id":"5","type":"expenses"},{"id":"6","type":"expenses"}]},"bills":{"data":[]}}}]}

NEW_GROUP_JSON = {"id":"1", "data":{"id":"1","type":"groups","attributes":{"name":"Cubs"},"relationships":{"memberships":{"data":[{"id":"1","type":"memberships"},{"id":"2","type":"memberships"},{"id":"3","type":"memberships"}]},"members":{"data":[{"id":"1","type":"users"},{"id":"2","type":"users"},{"id":"3","type":"users"}]},"events":{"data":[{"id":"1","type":"events"}]},"expenses":{"data":[{"id":"1","type":"expenses"},{"id":"2","type":"expenses"},{"id":"3","type":"expenses"},{"id":"4","type":"expenses"},{"id":"5","type":"expenses"},{"id":"6","type":"expenses"}]}}}}

NEW_EVENT_JSON = {"id":"1", "data":{"id":"1","type":"events","attributes":{"name":"Roadtrip","start-date":"2016-06-04T00:00:00.000Z","end-date":"2016-06-06T00:00:00.000Z","settled?":false,"group-id":1,"total":255.49},"relationships":{"group":{"data":{"id":"1","type":"groups"}},"memberships":{"data":[{"id":"1","type":"memberships"},{"id":"2","type":"memberships"},{"id":"3","type":"memberships"}]},"members":{"data":[{"id":"1","type":"users"},{"id":"2","type":"users"},{"id":"3","type":"users"}]},"expenses":{"data":[{"id":"1","type":"expenses"},{"id":"2","type":"expenses"},{"id":"3","type":"expenses"},{"id":"4","type":"expenses"},{"id":"5","type":"expenses"},{"id":"6","type":"expenses"}]},"bills":{"data":[]}}}}

NEW_USER_JSON = {"data":{"id":"1","type":"users","attributes":{"first_name":"Anthony","last_name":"Rizzo","password":"password","email":"arizzo@gmail.com","phone":"1111111111"},"relationships":{"memberships":{"data":[{"id":"1","type":"memberships"}]},"groups":{"data":[{"id":"1","type":"groups"}]},"events":{"data":[{"id":"1","type":"events"}]},"expenses":{"data":[{"id":"1","type":"expenses"},{"id":"2","type":"expenses"},{"id":"3","type":"expenses"}]},"bills":{"data":[]}}}}

NEW_MEMBER_JSON = {"data":[{"id":"1","type":"users","attributes":{"first_name":"Anthony","last_name":"Rizzo","password":"password","email":"arizzo@gmail.com","phone":"1111111111"},"relationships":{"memberships":{"data":[{"id":"1","type":"memberships"}]},"groups":{"data":[{"id":"1","type":"groups"}]},"events":{"data":[{"id":"1","type":"events"}]},"expenses":{"data":[{"id":"1","type":"expenses"},{"id":"2","type":"expenses"},{"id":"3","type":"expenses"}]},"bills":{"data":[]}}},{"id":"2","type":"users","attributes":{"first_name":"Kris","last_name":"Bryant","password":"password","email":"kbryant@gmail.com","phone":"2222222222"},"relationships":{"memberships":{"data":[{"id":"2","type":"memberships"}]},"groups":{"data":[{"id":"1","type":"groups"}]},"events":{"data":[{"id":"1","type":"events"}]},"expenses":{"data":[{"id":"4","type":"expenses"},{"id":"5","type":"expenses"}]},"bills":{"data":[]}}},{"id":"3","type":"users","attributes":{"first_name":"Brad","last_name":"Lindgren","password":"password","email":"bplindgren91@gmail.com","phone":"3333333333"},"relationships":{"memberships":{"data":[{"id":"3","type":"memberships"}]},"groups":{"data":[{"id":"1","type":"groups"}]},"events":{"data":[{"id":"1","type":"events"}]},"expenses":{"data":[{"id":"6","type":"expenses"}]},"bills":{"data":[]}}}]}
